# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml

    - name: Test
      run: mvn test

    - name: Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

    - name: Upload JAR Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: target/*.jar

    - name: Upload JAR via FTP
      if: success()
      run: |
        FILE=$(find target -maxdepth 1 -name "*.jar" | head -n 1)

        if [ -z "$FILE" ]; then
          echo "Keine JAR-Datei gefunden."
          exit 1
        fi

        cp "$FILE" target/lmikota.jar

        curl -T target/lmikota.jar \
          --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
          ftp://${{ secrets.FTP_SERVER }}/